const ACCOUNT = {
  REQUEST: "ACCOUNT_REQUEST",
  REQUEST_ERROR: "ACCOUNT_REQUEST_ERROR",
  REQUEST_SUCCESS: "ACCOUNT_REQUEST_SUCCESS",
  REQUEST_SIGNUP_SUCCESS: "ACCOUNT_REQUEST_SIGNUP_SUCCESS",
  REQUEST_LOGOUT_SUCCESS: "ACCOUNT_REQUEST_LOGOUT_SUCCESS",
  REQUEST_AUTHENTICATED_SUCCESS: "ACCOUNT_REQUEST_AUTHENTICATED_SUCCESS",
};

const STOCK_INFO = {
  REQUEST: "STOCK_INFO_REQUEST",
  REQUEST_ERROR: "STOCK_INFO_REQUEST_ERROR",
  REQUEST_QUOTE_SUCCESS: "STOCK_INFO_REQUEST_QUOTE_SUCCESS",
  REQUEST_TOPSTOCKS_SUCCESS: "STOCK_INFO_REQUEST_TOPSTOCKS_SUCCESS",
};

export { ACCOUNT, STOCK_INFO };
