const ACCOUNT = {
  REQUEST: "ACCOUNT_REQUEST",
  REQUEST_ERROR: "ACCOUNT_REQUEST_ERROR",
  REQUEST_SUCCESS: "ACCOUNT_REQUEST_SUCCESS",
  REQUEST_SIGNUP_SUCCESS: "ACCOUNT_REQUEST_SIGNUP_SUCCESS",
  REQUEST_LOGOUT_SUCCESS: "ACCOUNT_REQUEST_LOGOUT_SUCCESS",
  REQUEST_AUTHENTICATED_SUCCESS: "ACCOUNT_REQUEST_AUTHENTICATED_SUCCESS",
};

const ACCOUNT_INFO = {
  REQUEST: "ACCOUNT_INFO_REQUEST",
  REQUEST_ERROR: "ACCOUNT_INFO_REQUEST_ERROR",
  REQUEST_SUCCESS: "ACCOUNT_INFO_REQUEST_SUCCESS",
};

export { ACCOUNT, ACCOUNT_INFO };
