const ACCOUNT = {
  REQUEST: "ACCOUNT_REQUEST",
  REQUEST_ERROR: "ACCOUNT_REQUEST_ERROR",
  REQUEST_LOGIN_SUCCESS: "ACCOUNT_REQUEST_SUCCESS",
  REQUEST_SIGNUP_SUCCESS: "ACCOUNT_REQUEST_SIGNUP_SUCCESS",
  REQUEST_LOGOUT_SUCCESS: "ACCOUNT_REQUEST_LOGOUT_SUCCESS",
  REQUEST_AUTHENTICATED_SUCCESS: "ACCOUNT_REQUEST_AUTHENTICATED_SUCCESS",
};

const ACCOUNT_STOCKS = {
  REQUEST: "ACCOUNT_STOCKS_REQUEST",
  REQUEST_ERROR: "ACCOUNT_STOCKS_REQUEST_ERROR",
  REQUEST_ADD_SUCCESS: "ACCOUNT_STOCKS_REQUEST_ADD_SUCCESS",
  REQUEST_DELETE_SUCCESS: "ACCOUNT_STOCKS_REQUEST_DELETE_SUCCESS",
  REQUEST_ALLSTOCKS_SUCCESS: "ACCOUNT_STOCKS_REQUEST_ALLSTOCKS_SUCCESS",
  RESET: "ACCOUNT_STOCKS_DATA_RESET",
};

const YAHOO = {
  REQUEST: "YAHOO_REQUEST",
  REQUEST_ERROR: "YAHOO_REQUEST_ERROR",
  REQUEST_QUOTE_SUCCESS: "YAHOO_REQUEST_QUOTE_SUCCESS",
  REQUEST_TOPGAINERS_SUCCESS: "YAHOO_REQUEST_TOPGAINERS_SUCCESS",
  RESET: "YAHOO_DATA_RESET",
};

export { ACCOUNT, ACCOUNT_STOCKS, YAHOO };
